### ISSUE TITLE
Unicode example crashes with Amethyst Vulkan backend

### ISSUE THREAD

**Issue by e-user** [amethyst/bracket-lib#127]
When running `cargo run --example unicode --features amethyst_engine_vulkan --no-default-features` in `bracket-terminal-0.8.1`, the program crashes with

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `33554432`,
 right: `25165824`: Size of must match size of the image region'
```

Intriguingly, the two integers have a ratio of 3 to 4.

I'm running Rust on Fedora Silverblue Linux x86_64.
```
cargo 1.45.0-nightly (cb06cb269 2020-05-08)
rustc 1.45.0-nightly (bad3bf622 2020-05-09)
```

[stacktrace.log](https://github.com/thebracket/bracket-lib/files/4609625/stacktrace.log)

**Comment by thebracket** [comment]
Currently, yes it does - I haven't implemented the extended character handling into the Amethyst code. It's actually quite a bit behind, missing various fancy and sprite features also. I'll try and catch up on that, but I've been delaying Amethyst support while they make some big changes; when they finish their Legion port, I'll have to basically rewrite it anyway.

**Comment by thebracket** [comment]
Closing this because Amethyst back-end support is being replaced with `wgpu`. The Unicode example works in the current development branch, using wgpu/vulkan and wgpu/dx12 (it probably works on metal, but I forgot to bring my Mac with me today). See #237
