### ISSUE TITLE
Replace `BError` with `BResult<T>`

### ISSUE THREAD

**Issue by Deuchier** [amethyst/bracket-lib#193]
I see that the type BError is a convenient type that wraps around the standard Error type. However, it is restricted to returning nothing. If we extend it by allowing a generic parameter for the returning type, we'll be able to write functions such as this:

```rust
fn build_context() -> BResult<BTerm> {
    BTermBuilder::simple(WIDTH, HEIGHT)?
        .build()
}
```

I also suggest replacing the current `dyn Error` with `anyhow::Error`, which is easier to use, to extend, and has better performance.

**Comment by thebracket** [comment]
This is an interesting idea, and I'm going to play around with it a bit. My biggest concern is breaking compatibility with the code that's already out there, particularly Hands-on Rust. So I'll play around a bit and see what I can come up with. Thanks for the suggestion!

**Comment by thebracket** [comment]
I'll push a new branch, `193_berror` in a moment. It offers a `BResult` syntax, a new example `return_error` in `bracket-terminal` to demonstrate it, and has been tested with native, WASM, Curses, Cross_term and Amethyst_engine_Vulkan features. I think it'll meet your needs. I'll look at mainlining it after a few more tests.

**Comment by thebracket** [comment]
I think I like this. It allows your example above, and also retains `BError` compatibility with existing code.

```rust
use bracket_terminal::prelude::*;

bracket_terminal::add_wasm_support!();

struct State {}

impl GameState for State {
    fn tick(&mut self, ctx: &mut BTerm) {
        ctx.print(1, 1, "Hello Bracket World");
    }
}

fn build_context() -> BResult<BTerm> {
    BTermBuilder::simple80x50()
        .with_title("Hello Minimal Bracket World")
        .build()
}

fn main() -> BError {
    let context = build_context()?;
    let gs: State = State {};

    main_loop(context, gs)
}
```

**Comment by thebracket** [comment]
I'll mark this as "awaiting confirmation" - does that suit your needs?

**Comment by Deuchier** [comment]
Wow! I'm really excited. I'm yet a student and has just started my way towards a career of game development. It's the first time I propose an idea and get accepted by an established programmer.

I gonna boast about it to my friends XP
