### ISSUE TITLE
Wrong FOV near the corners

### ISSUE THREAD

**Issue by LEGOL2** [amethyst/bracket-lib#198]
Hello!
The problem is only partially fixed. Field of vision near the corners is too small and causes monsters to get stuck on the edges. Please take a look at below images.
![1](https://user-images.githubusercontent.com/22496424/110236412-04c65380-7f36-11eb-9dbb-d5b8a95544aa.PNG)
![2](https://user-images.githubusercontent.com/22496424/110236388-d6e10f00-7f35-11eb-9df6-a4e88ad8802d.PNG)

As you can see, the player or monster does not have a vision on 2nd tile, while staying on the wall edge. It will not try to move towards the player and just stay there. I've checked with book source code, and behavior is different.
![3](https://user-images.githubusercontent.com/22496424/110236505-76060680-7f36-11eb-9a7d-a6807f028fcd.PNG)

Edit: @thebracket adding mention, so you get a notification, because I can't reopen the issue.

Edit2: I've originally posted this in #192 but I've decided to create new issue.

_Originally posted by @LEGOL2 in https://github.com/amethyst/bracket-lib/issues/192#issuecomment-792251614_

**Comment by dvidbruhm** [comment]
I can confirm that I have the same issue, and after some fiddling i've found that the issue disappears If I downgrade bracket-pathfinding from 0.8.4 -> 0.8.1.

**Comment by QuinnStevens** [comment]
I'm experiencing this problem too. It's a bit annoying when trying to test certain things, as I can't get enemies to follow me through corridors unless they're perfectly lined up.

**Comment by SPuntte** [comment]
Hello, and thank you @thebracket for this amazing library! :heart:

While following along the tutorial, I also noticed this behavior and wanted to address it. To be honest, I didn't really try to understand the current algorithm but replaced it with a pretty straightforward adaptation of [Albert Ford's symmetric shadowcasting](https://www.albertford.com/shadowcasting/).

I'm not sure if my code is up to the library's standards but I can make a PR if that's something you want to see. Quick benchmarking shows the replacement being around 2-3x slower than the current one so there's definitely room for optimization. The use of rational numbers (which Ford advocates for) adds a dependency, `num-rational`. I also switched trait objects for generics, which is of course reversible if you prefer the former.

Finally a couple images, inspired by OP's examples, for illustration of the differences in behavior:
![bracket-lib1](https://user-images.githubusercontent.com/8291097/130709614-b336d491-9768-434a-a1ce-ab417461c86c.png)
![bracket-lib2](https://user-images.githubusercontent.com/8291097/130709622-58599689-5eb8-4436-ae49-edbdbe2294e0.png)
- dark cyan background: FOV origin
- white: within FOV of both algorithms
- green: within FOV of the new algorithm only
- red: within FOR of the old algorithm only
- dark magenta background: a `BresenhamCircle` for reference

**Comment by LEGOL2** [comment]
My humble opinion is that you could add this as a new function and create new interface for this specific algorithm, so that user can select which fov he wants.

**Comment by thebracket** [comment]
I've merged in the PR (with a couple of tweaks to also merge in some Clippy fixes - nothing major), and it seems to work well. That PR was awesome - thank you. I tested with both Hands-on Rust and the tutorial code and absolutely nothing broke. :-)

**Comment by SPuntte** [comment]
Whoops, I hope you don't mind the delay. Great news! Happy to contribute :)

**Comment by LEGOL2** [comment]
@SPuntte thank you very much for PR!
