### ISSUE TITLE
panic at startup when running in 5120x1440 resolution

### ISSUE THREAD

**Issue by gnarlie** [amethyst/bracket-lib#216]
When running in high resolution, I'm getting a panic from OpenGL. Runs fine up to 3840x2160. Any suggestions?

```
hread 'main' panicked at '[GL] Error: INVALID_ENUM', /home/badams/.cargo/registry/src/github.com-1ecc6299db9ec823/bracket-terminal-0.8.2/src/hal/gl_common/glerror.rs:20:36
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:519:12
   1: bracket_terminal::hal::gl_common::glerror::gl_error
             at /home/badams/.cargo/registry/src/github.com-1ecc6299db9ec823/bracket-terminal-0.8.2/src/hal/gl_common/glerror.rs:20:36
   2: bracket_terminal::hal::gl_common::font::Font::setup_gl_texture
             at /home/badams/.cargo/registry/src/github.com-1ecc6299db9ec823/bracket-terminal-0.8.2/src/hal/gl_common/font.rs:131:9
   3: bracket_terminal::hal::native::mainloop::main_loop
             at /home/badams/.cargo/registry/src/github.com-1ecc6299db9ec823/bracket-terminal-0.8.2/src/hal/native/mainloop.rs:74:13
   4: bracket_terminal::bterm::main_loop
             at /home/badams/.cargo/registry/src/github.com-1ecc6299db9ec823/bracket-terminal-0.8.2/src/bterm.rs:1062:5
   5: roguelike::main
             at ./src/main.rs:127:5
   6: core::ops::function::FnOnce::call_once
             at /home/badams/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
```

rltk 0.8.0

**Comment by thebracket** [comment]
I don't have anything that can display that resolution. Seeing the `BAD_ENUM` there makes me think that the backing texture creation failed - that's *usually* GL being denied sufficient video memory, or being unable to create a texture with the requested type. IIRC, the texture type is pulled from what GL reports it uses for the main display (which it has to support, obviously). What's your video card?

**Comment by gnarlie** [comment]
My video card is  GTX 1080, running the nvidia native drivers (v 460.80) on Ubuntu 20.04.

According to nvidia-smi, video memory usage is 504MB/8116MB if that helps. Are there any OpenGL logs that might be useful?

**Comment by gnarlie** [comment]
Quick update - I've got the system running at full resolution. I switched from using i3 window manager to Gnome and everything just works. Closing because I've got it working.
