### ISSUE TITLE
Cannot compile `bracket-terminal`

### ISSUE THREAD

**Issue by ioboi** [amethyst/bracket-lib#218]
I tried building `bracket-terminal` using:

````
cargo build --all --target wasm32-unknown-unknown --release --features=opengl
```` 

and received the following error:

````
--> bracket-terminal/src/hal/wasm/mainloop.rs:9:9
  |
9 |     use glow::HasRenderLoop;
  |         ^^^^^^^^^^^^^^^^^^^ no `HasRenderLoop` in the root

error[E0433]: failed to resolve: could not find `RenderLoop` in `glow`
  --> bracket-terminal/src/hal/wasm/mainloop.rs:33:29
   |
33 |     let render_loop = glow::RenderLoop::from_request_animation_frame();
   |    
[...]
````

I think the error is caused because of the recent upgrade to `glow:0.10.0`.

**Comment by thebracket** [comment]
Oh no! I'll look into that today. Thanks!

**Comment by thebracket** [comment]
Wow, I wish I hadn't accepted that PR! The `glow` render loop handler has completely changed. Going to have to rework a chunk of code.

**Comment by thebracket** [comment]
Ok, it's a bit messier than I like, but it now uses `web-sys` for requesting animation frames (which requires some slightly odd memory stuff). The examples run pretty well for me (e.g. https://bfnightly.bracketproductions.com/wasmtest3/sprites/ ). Still need to test with the roguelike tutorial.

**Comment by thebracket** [comment]
And here's a working Roguelike tutorial chapter: https://bfnightly.bracketproductions.com/rustbook/wasm_12/chapter-74-darkcity/

I think this is going to work. I'll run a few more tests and push the updated crate.

**Comment by ioboi** [comment]
Thank you for the prompt reaction and fix 👍

**Comment by thebracket** [comment]
Ok, it passed the tests I threw at it - pushing the crate now. Thanks!
