### ISSUE TITLE
Memory usage out of control when dragging the window?

### ISSUE THREAD

**Issue by scambier** [amethyst/bracket-lib#224]
I'm on Windows 10.

When starting the game, the RAM usage is at about 25MB. But as soon as I start dragging the window across the screen, the RAM usage increases at a rapid pace without stopping, to the point of reaching 2GB+ after a few seconds.

I was able to reproduce this with the [chapter 2 tutorial code](https://github.com/amethyst/rustrogueliketutorial/tree/master/chapter-02-helloecs)

![image](https://user-images.githubusercontent.com/3216752/131137275-9b7ff7dd-8028-43b1-8070-1c3dcde991ec.png)

![image](https://user-images.githubusercontent.com/3216752/131137551-ed0a795e-85de-4b14-a899-6c49c7603967.png)

**Comment by BiosElement** [comment]
I can replicate this as well. In just a couple seconds I went from 12mb to over 7 Gigs.

**Comment by thebracket** [comment]
This *should* have been alleviated in the recent #239 and #241 patches. It now only calls `on_resize` when tick time comes around, reducing the overhead quite a lot. It looks decent on my Mac and Windows machines. Could you give it a go, please?

**Comment by scambier** [comment]
Just to make sure, is this the right config for cargo.toml?

```toml
[dependencies.bracket-lib]
branch = "scaling"
features = ["serde"]
git = "https://github.com/amethyst/bracket-lib"
```

I tried on my own project: the memory usage rises way more slowly, up until ~50-60MB. Then it explodes like before, hitting 2GB+ in a few seconds. You really have to drag and resize the window for at least 30 seconds to trigger the exponential ram usage, so definitely not something that could happen in a normal use.

Also, maybe related to those changes, the framerate seems to capped at 30fps (with or without vsync)

**Comment by thebracket** [comment]
You can switch to the master branch - the feature has been merged now. Good to see it improved, even if it isn't fixed - I'll see if I can torture test it a bit more.

The FPS cap at 30 is the new default. You can add a `with_fps_cap(x)` to your initialization to change it. Most users are implementing slow-moving roguelikes, so that's a fair default for them - and keeps CPU usage way down.

**Comment by scambier** [comment]
I tried it again today, and it looks fixed 👍 

Thank you
