### ISSUE TITLE
Part of the font not rendering when using no_bg console

### ISSUE THREAD

**Issue by farbanas** [amethyst/bracket-lib#226]
I've been going through the Hands on Rust book and I've noticed that parts of the monsters do not get rendered. It's been bugging me why that happens, but I can't seem to understand why. 

When I change the console to which those monsters are rendered from `simple_console_no_bg` to `simple_console`, those monsters get rendered completely.

![second_ss](https://user-images.githubusercontent.com/68274365/132059531-e64d83fd-c170-477c-b2e1-b2d8a0bd62cd.png)
![first_ss](https://user-images.githubusercontent.com/68274365/132059525-306512fe-5617-498b-b624-0a9197c34ecf.png)

**Comment by thebracket** [comment]
#239 has fixed this in `wgpu` mode. I've backported the fix to GL/WebGL - a commit will appear in a moment that fixes this.
