### ISSUE TITLE
Consider tagging commits released to crates.io

### ISSUE THREAD

**Issue by Ozaq** [amethyst/bracket-lib#229]
I am currently working trough your very fun 'Hands-on Rust' book and while doing so I was stumped by the behaviour of `DrawBatch::Submit` and its surprising implementation. However when checking your repository I found Issue #140 in which you mentioned this as already fixed. Long story short: I finally figured out that the last upload to crates.io was 2 days before the fix for #140 was merged to master.

Currently it is harder than necessary to figure out which commit has been released under which version number to crates.io. in case I want to report an issue.

Please consider adding release tags to this repository.

Cheers

**Comment by thebracket** [comment]
I tagged this one, and will try to remember to tag new ones. :-)

**Comment by Ozaq** [comment]
Thank you very much!
