### ISSUE TITLE
error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES

### ISSUE THREAD

**Issue by achenet** [amethyst/bracket-lib#243]
Hello,

Whilst working through the book Hands On Rust, I encounter the following problem when trying to `cargo run` the `flappy` project. 

```
#version 330 core
layout (location = 0) in vec3 aPos;
layout (location = 1) in vec4 aColor;
layout (location = 2) in vec4 bColor;
layout (location = 3) in vec2 aTexCoord;

out vec4 ourColor;
out vec4 ourBackground;
out vec2 TexCoord;

void main()
{
        gl_Position = vec4(aPos, 1.0);
        ourColor = aColor;
        ourBackground = bColor;
        TexCoord = vec2(aTexCoord.x, aTexCoord.y);
}
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES

thread 'main' panicked at 'explicit panic', /home/utilisateur/.cargo/registry/src/github.com-1ecc6299db9ec823/bracket-terminal-0.8.5/src/hal/gl_common/shader.rs:26:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

I suspect the issue is something to do with my OpenGL Shading Language not being up to date enough for the `bracket-lib ~0.8.1` used, but am rather at a loss when it comes to possible solutions. 

Any help would be greatly appreciated.

**Comment by thebracket** [comment]
What platform are you using? OpenGL 3.3 is usually pretty safe to target. I
have ES working in web assembly, so I should be able to come up with a
compatibility feature to use it on desktop if needs-be.

(On mobile, hopefully this formats ok)

**Comment by achenet** [comment]
Thank you for your reply, the format is good. :)

I am running Ubuntu 20.04 on an old (pre-2015) Lenovo Thinkpad X201. If there are any commands I should type into terminal to give more precise information, please let me know.

Could you please explain what ES is exactly ? I apologize, I'm rather new to this sort of thing. 

You mentioned Web Assembly. I know that it is possible to compile Rust to Web Assembly. As such, would it be possible to try to get the program to compile to WebASM and therefore hopefully bypass the issue by executing the game in a browser?

**Comment by thebracket** [comment]
If I remember rightly, you need to either use `mesa` (which provides GL support) or updated drivers - the latter especially if you are using nVidia. 

Setting the environment variable `MESA_GL_VERSION_OVERRIDE=3.3` often helps. So you could try running with: `MESA_GL_VERSION_OVERRIDE=3.3 MESA_GLSL_VERSION_OVERRIDE=330 cargo run`.

The command `glxinfo` will show your OpenGL information, if you could provide the output of that I may be able to dig up some more. I've had it working on a 2014 ThinkPad a few versions ago (the laptop has since died), so I know it's possible!

**Comment by achenet** [comment]
Thank you for your reply. 

I tried what you suggested:
I typed in 
```
export MESA_GL_VERSION_OVERRIDE=3.3
export MESA_GLSL_VERSION_OVERRIDE=330
```

to set the values of those environment variables before doing `cargo run`, and it worked! ^_^

Thank you very much for your help, and seeing as how I believe you are also the author of both the book and the lib, thank your for making those as well. :)

Wishing you all the best,
