### ISSUE TITLE
Transparency not working with fancy console

### ISSUE THREAD

**Issue by tobyhede** [amethyst/bracket-lib#250]
I have a png with transparent background. 

When I render a glyph using a fancy console, the background color is rendered. 
I've tried `ctx.set` and `ctx.set_fancy` 

Using `with_simple_console_no_bg` renders the glyph correctly.  

The code is very vanilla, setup console and render in tick.

```
 BTermBuilder::new().with_fancy_console( /* etc */);

        ctx.set_active_console(0);
        // ctx.set(
        //     10,
        //     10,
        //     WHITE,
        //     WHITE,
        //     16,
        // );

        let pos = PointF::new(10.0, 5.0);
        let zorder= 1;
        let angle = Degrees::new(0.0);
        let scale = PointF::new(1.0,1.0);

        ctx.set_fancy(pos, zorder, angle, scale, WHITE, WHITE, 16);
```

**Comment by jasonjmcghee** [comment]
You're setting the background to be `WHITE` here. Maybe you want to set the background to be transparent?

```rust
RGBA::from_f32(0.0, 0.0, 0.0, 0.0)
```

or concise
```rust
RGBA::new()
```

In a simple test this seems to work as expected for me.

**Comment by tobyhede** [comment]
Thanks @jasonjmcghee ... that's the magic incantation I was missing!
