### ISSUE TITLE
 compilations errors with rust 1.60.0

### ISSUE THREAD

**Issue by sbergot** [amethyst/bracket-lib#263]
Hello,

I have upgraded this morning and have compilation errors in the point.rs file from bracket-geometry. There seems to be a type problem between i32 and f32. I am a rust noob but I will try to provide a PR.

**Comment by sbergot** [comment]
Nevermind. The issue was with my cargo registry cache.

**Comment by thebracket** [comment]
Thank you! I was just updating my dev system to try and find the issue!
