### ISSUE TITLE
Lagging with git branch

### ISSUE THREAD

**Issue by lecoqjacob** [amethyst/bracket-lib#275]
I noticed some very strange behavior when using the git branch directly, versus the version number. Here are my two setups:

Scenario 1 has fluent movement using versions directly in cargo.toml
```rust
[dependencies]
bracket-lib = {version = "~0.8.1", features = ["serde"]}
rayon = {version = "1.5.3", optional = true}
specs = {version = "~0.18.0", default_features = false, features = [
  "parallel",
  "derive",
]}
```
![CleanShot 2022-07-14 at 19 34 24](https://user-images.githubusercontent.com/9278174/179123494-e8eee5ad-ee11-4a5c-8323-5ed54a77aa0b.gif)

Scenario 2 has lagged movement
```rust
[dependencies]
bracket-lib = {git = "https://github.com/amethyst/bracket-lib", features = ["serde"]}
# bracket-lib = {version = "~0.8.1", features = ["serde"]}
rayon = {version = "1.5.3", optional = true}
specs = {version = "~0.18.0", default_features = false, features = [
  "parallel",
  "derive",
]}
```
![CleanShot 2022-07-14 at 19 38 27](https://user-images.githubusercontent.com/9278174/179123796-bddb8eca-ab82-4a28-9e23-bf8d0db8d960.gif)

As you can see using the git branch directly causes input lag when using turn states. This is pulled straight from your roguelike 2019 tutorial from `amethyst`. Are versions more production ready than pulling the branch directly or is there a bug not in the latest version?

**Comment by thebracket** [comment]
I think this is being caused by the "spin sleep" that was added to lower CPU usage. My testing seems to show this is the case. I'll have a commit (in the bevy branch, because that's where I'm doing some cleanup pre-merge) in a moment to test it with.

**Comment by lecoqjacob** [comment]
Oh wow! Thanks for the fix. I'll close this as resolved
