### ISSUE TITLE
Console Sizing Issues

### ISSUE THREAD

**Issue by lecoqjacob** [amethyst/bracket-lib#296]
I'm trying to figure out if I'm crazy, or if there is a bug within bracket lib. I creates an 80x50 simple console and populated it with a floor and some mountain ranges (just using 'n' char), but the console seems extremely small. 

<img width="1512" alt="CleanShot 2022-09-26 at 18 26 09@2x" src="https://user-images.githubusercontent.com/9278174/192398886-db26ae1c-9d5b-4e5c-9766-59a0ab5f9f44.png">

i wanted the window to be around 960x720 for better readability, but if I increase the console size, it only changes how many pixels are drawn.

This is 120x90 console.

<img width="1512" alt="CleanShot 2022-09-26 at 18 36 17@2x" src="https://user-images.githubusercontent.com/9278174/192399025-cd32bc0d-1208-405c-bb06-d08b1c2f2cf4.png">

Im on a m1 mac and these are my specs.

<img width="585" alt="CleanShot 2022-09-26 at 18 36 55@2x" src="https://user-images.githubusercontent.com/9278174/192399052-cd337d34-8025-4b64-b8de-67a8dc4eff18.png">

**Comment by lecoqjacob** [comment]
Did some digging and started playing around with `with_tile_diomension` and `with_demension` to achieve what I wanted. I noticed something very interesting between the deployed code and your git branch. With this setup im using `terminal8x8` but with tilesize of 12.
<img width="802" alt="CleanShot 2022-09-27 at 11 21 42@2x" src="https://user-images.githubusercontent.com/9278174/192581222-a60ec27a-dc56-46b0-8fa1-5b6dfaf0c352.png">

On the git branch there is pixel tearing:

<img width="613" alt="CleanShot 2022-09-27 at 11 22 28@2x" src="https://user-images.githubusercontent.com/9278174/192581361-dd636b42-4ab5-422b-ba6b-89caa1fadc34.png">


but on the `0.8` version from crates.io, there is no tearing:

<img width="665" alt="CleanShot 2022-09-27 at 11 23 01@2x" src="https://user-images.githubusercontent.com/9278174/192581470-c1fde30a-3e17-4b9f-b6fe-ede81614a0b3.png">

**Comment by lecoqjacob** [comment]
Digging backwards in the commits, the problem starts whenever Scalar2 was introduced https://github.com/amethyst/bracket-lib/commit/4b475077ccf3bd67d196dfed94d4d719118934a2

**Comment by thebracket** [comment]
I'm wondering if your initialization is actually what you want to do? Using the `simple` constructor gets you a simple terminal, and then you're loading a "fancy" terminal as the second layer - and you're setting the font size for that one? I don't see tearing when I use:

```rust
    let context = BTermBuilder::new()
        .with_font("terminal8x8.png", 8, 8)
        .with_fancy_console(80, 50, "terminal8x8.png")
        .with_tile_dimensions(12, 12)
        .build()?;
```

With that said, if you want a 12x12 - I'd recommend grabbing a font of that size. There are some great ones here: https://dwarffortresswiki.org/Tileset_repository#12.C3.9712

**Comment by lecoqjacob** [comment]
Interesting. I believe it mainly happens with the horizontal bar.  I updated the example to just draw a bar across the screen. That being said, if I use a 12x12 font, the tearing seems to not happen. I should also note using the 8x8 font, and then forcing the tile_size to (16,16) doesn't cause tearing either. So I guess its the 1.5x difference for the 8x8 font which causes some weird scaling issues

<img width="1017" alt="CleanShot 2022-10-04 at 13 39 52@2x" src="https://user-images.githubusercontent.com/9278174/193899673-bfb9806f-73d9-48ad-80d6-e402a230080f.png">

**Comment by thebracket** [comment]
That makes sense. Sorry for the lack of replies, I set aside time this week
- and the whole family is out sick. :-(
I'm now trying to clear up a big chunk of next week for bracket-lib.
