### ISSUE TITLE
book unavailable

### ISSUE THREAD

**Issue by dimitrilw** [amethyst/bracket-lib#349]
I realize this is not a repo-specific issue; however, I am unsure where else to report it.

<img width="459" alt="image" src="https://github.com/amethyst/bracket-lib/assets/5898931/3a796182-ebdd-425b-9207-14d57abb65b6">

For that matter, all of `http://bracketproductions.com/` is not resolving.

<img width="404" alt="image" src="https://github.com/amethyst/bracket-lib/assets/5898931/bd7a13bd-015c-4a59-8ad9-4aff375c85d7">

Is there an alternate site for the book? Something like `https://amethyst.github.io/bracket-lib`? (no book there; hence I did not make it a clickable URL)

**Comment by thebracket** [comment]
Oh no! I'll try and figure out what went wrong with my DNS. Thanks for
letting me know! We had a HUGE power outage last night, which may be
related.

**Comment by thebracket** [comment]
I think it's back up (it's resolving here). I'm on a Digital Ocean droplet,
but my DNS setup could be better (it's been stable for years, so I hadn't
messed with it).
