### ISSUE TITLE
Issue running examples from the book on NixOS with Wayland (Plasma6)

### ISSUE THREAD

**Issue by paul-jewell** [amethyst/bracket-lib#360]
Good evening!
First of all thanks for the Book - it's excellent reading :)
I have hit a problem which I am struggling to resolve. I am following the book code on my laptop, which has NixOS installed, and is running Plasma 6 (unstable). 
When I "cargo run" the first version of the flappy dragon code, I get the following error:
```
thread 'main' panicked at /home/paul/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.27.5/src/platform_impl/linux/mod.rs:719:9:
Failed to initialize any backend! Wayland status: NoWaylandLib X11 status: LibraryOpenError(OpenError { kind: Library, detail: "opening library failed (libX11.so.6: cannot open shared object file: No such file or directory); opening library failed (libX11.so: cannot open shared object file: No such file or directory)" })
```
Do I need to do anything special to ensure bracket-lib uses wayland libraries as opposed to X11? I have had a good look in the material around here, but failed to find anything specific. I suspect the nix approach to libraries may be responsible for the NoWaylandLib message.  Perhaps I should have a dig through the code to see what is being looked for to generate this message.

I have found reference to Wayland in the closed issues, so it seems to work elsewhere. I am quite happy to accept I need to configure something on my system completely unrelated to the book code or the library!

Many thanks. If I find a resolution before you get to this issue, I will comment for others and close this.

**Comment by thebracket** [comment]
I'm on mobile traveling, but it looks like it wants the Wayland X11
support. Wayland won't run at all on my usual dev box, which makes
supportive it tough!

**Comment by paul-jewell** [comment]
No worries! Apologies for the slow response, but the fact I had issues with this has finally spurred me on to move away from NixOS. I have an issue on Gentoo as well under Wayland, but a different one. When I start an X session, everything works as expected, so I will just use X when working with the code from the Book.
PS: Good to see the new book appear in PragProg as a Beta. I will get a copy, but only after finishing this one!
